Fix mongodb kinetic
shadow-robot/sr_interface pull request #237
Opened 2017-02-03 15:33 UTC by beatrizleon

merge after #230 

Fixes #233

2017-02-03 18:14 UTC, toliver commented
So let's wait until jenkins build passes to merge this one.

2017-02-09 17:01 UTC, toliver requested changes

2017-02-09 17:01 UTC, toliver commented on repository.rosinstall
> +- git:
This is not a ROS package, so it should be installed through some other mechanism. (e.g. ansible role)

2017-02-09 17:10 UTC, beatrizleon commented on repository.rosinstall
> +- git:
ok

2017-02-22 16:51 UTC, toliver requested changes
If it partially solves the issue, can you comment on what is missing?

2017-02-22 16:51 UTC, toliver commented on sr_moveit_hand_config/package.xml
> +  <build_depend>scons</build_depend>
Do this package really depend on scons, or is this a trick to facilitate the installation of mongodb?
If so, please add a comment in the package.xml

2017-02-22 18:02 UTC, beatrizleon commented on sr_moveit_hand_config/package.xml
> +  <build_depend>scons</build_depend>
Yes, it is only needed for installing the mongo-cxx-driver. As we are not longer installing it here, I am going to remove the dependency

2017-02-22 18:03 UTC, beatrizleon commented
I updated pr description and add a link to instructions to build it

2017-02-22 18:31 UTC, merged