F save targets
shadow-robot/sr_interface pull request #240
Opened 2017-02-06 15:46 UTC by dg-shadow

2017-02-07 13:14 UTC, toliver commented on sr_robot_commander/src/sr_robot_commander/sr_robot_state_saver.py
> +        self.__save_target = save_target
I hate these double leading underscores. We should always use single underscores.

2017-02-07 13:20 UTC, dg-shadow commented on sr_robot_commander/src/sr_robot_commander/sr_robot_state_saver.py
> +        self.__save_target = save_target
they have a purpose, but ok ;p

2017-02-07 13:21 UTC, dg-shadow commented on sr_robot_commander/src/sr_robot_commander/sr_robot_state_saver.py
> +        self.__save_target = save_target
As in, double underscore is technically more "correct" but happy to use the dirty, easier to type, single underscore if you insist

2017-02-07 13:22 UTC, dg-shadow commented on sr_robot_commander/src/sr_robot_commander/sr_robot_state_saver.py
> +        self.__save_target = save_target
Although either way, changing to all single _ would make the diff quite messy. maybe merge this one and I'll do a separate pr to change the underscores?

2017-02-08 14:52 UTC, toliver requested changes

2017-02-08 14:52 UTC, toliver commented on sr_example/scripts/sr_example/hand_examples/sr_hand_optoforce_tactile_example.py
> -#!/usr/bin/env python
Wow. Why does this appear as deleted?

2017-02-08 14:53 UTC, toliver commented on sr_robot_commander/src/sr_robot_commander/sr_robot_state_saver.py
> +        self.__save_target = save_target
Yes, indeed that would be a separate PR. And I mean it mainly for new files.

About it being more correct. that's far from true.

2017-02-10 11:50 UTC, dg-shadow commented on sr_example/scripts/sr_example/hand_examples/sr_hand_optoforce_tactile_example.py
> -#!/usr/bin/env python
No idea o.O

2017-07-10 14:23 UTC, beatrizleon commented
Closing this pr as #257 is now opened for kinetic

2017-07-10 14:23 UTC, closed without merging