Made same modifications made to fh_interface repo to create workshop …
shadow-robot/sr_interface pull request #263
Opened 2017-06-02 15:13 UTC by JamesAndrews3

…scene

Tested in simulation

2017-06-07 12:13 UTC, JamesAndrews3 commented
Tested in simulation - works as expected
NOT tested on real Hand E and UR10 in workshop!

2017-06-13 11:01 UTC, toliver requested changes

2017-06-13 11:01 UTC, toliver commented on sr_robot_launch/launch/sr_ur_arm_hand.launch
> +    <node if="$(arg scene)" pkg="fh_robot_launch" type="timed_roslaunch.sh" args="8 sr_moveit_hand_config scene.launch
There can't be a dependency on fh_robot_launch inside sr_interface.

There must be a copy of the script timed_roslaunch.sh somewhere in this repository I think.
Maybe ask Beatriz where.

2017-06-13 11:02 UTC, toliver requested changes

2017-06-13 11:02 UTC, toliver commented on sr_moveit_hand_config/launch/scene.launch
> +  <arg name="scene_file" default="$(find fh_description)/other/scenes/lab.scene"/>
Again, no dependencies on fh_... packages are allowed in sr_interface.

2017-06-14 09:57 UTC, toliver approved these changes

2017-06-14 12:11 UTC, beatrizleon commented on sr_robot_launch/scripts/timed_roslaunch.sh
> +#
This timed_roslaunch.sh is already in sr_interface in https://github.com/shadow-robot/sr_interface/tree/kinetic-devel/sr_multi_moveit/sr_multi_moveit_config/scripts so it doesn't need to be included again

2017-06-14 12:11 UTC, beatrizleon commented on sr_moveit_hand_config/launch/scene.launch
> +<launch>
This launch file should be better placed inside the moveit config of the hand and arm rather that in the hand config only as it is meant to be used when both are present. In my opinion it should be placed here: https://github.com/shadow-robot/sr_interface/tree/kinetic-devel/sr_multi_moveit/sr_multi_moveit_config/launch

2017-06-14 12:13 UTC, merged

2017-06-14 12:16 UTC, toliver commented
@beatrizleon Sorry I merged before I saw your comments. I have added your comments to a subtask to be done in this sprint.