F#src 3236 add biotac argument to control machine launch file
shadow-robot/sr_interface pull request #389
Opened 2019-05-21 12:38 UTC by carebare47

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropiate.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [ ] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [ ] Tested on real hardware (if appropriate)
￼

2019-05-21 12:43 UTC, beatrizleon commented on sr_robot_launch/launch/sr_left_ur10arm_hand.launch
>    <arg name="use_moveit" default="true"/>
please remove this file from this pr

2019-05-21 12:44 UTC, beatrizleon commented on sr_robot_launch/launch/hardware_control_loop.launch
> +  <arg if="$(eval hand_ctrl and biotacs)" name="robot_description" default="'$(find sr_multi_description)/urdf/right_srhand_ur10_bt_sp_biotacs.urdf.xacro'"/>
also replace the right with side

2019-05-21 12:45 UTC, beatrizleon requested changes
Replace the right with side

2019-05-21 13:19 UTC, carebare47 commented on sr_robot_launch/launch/hardware_control_loop.launch
> +  <arg if="$(eval hand_ctrl and biotacs)" name="robot_description" default="'$(find sr_multi_description)/urdf/right_srhand_ur10_bt_sp_biotacs.urdf.xacro'"/>
Oops, missed that, thanks :)

2019-05-30 12:24 UTC, beatrizleon approved these changes

2019-05-30 12:56 UTC, merged