F adding bimanual no hands
shadow-robot/sr_interface pull request #458
Opened 2020-02-10 13:27 UTC by mikramarc

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropiate.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [ ] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [ ] Tested on real hardware (if appropriate)
￼

2020-02-11 10:37 UTC, giusebar requested changes

2020-02-11 10:37 UTC, giusebar commented on sr_robot_launch/launch/sr_bimanual_hardware_control_loop.launch
> +      <param name="publish_frequency" type="double" value="250.0" />
pass argument

2020-02-11 12:59 UTC, beatrizleon commented on sr_robot_launch/launch/sr_bimanual_hardware_control_loop.launch
> +      <param name="publish_frequency" type="double" value="250.0" />
yes: robot_state_pub_frequency

2020-02-11 12:59 UTC, beatrizleon commented on sr_robot_launch/launch/sr_bimanual_hardware_control_loop.launch
> +          args="--wait-for=/ra_arm_ready ra_trajectory_controller "/>
are we supposed to remove this ones from here?

2020-02-12 12:34 UTC, beatrizleon approved these changes

2020-02-12 12:38 UTC, merged