F#src 3432 test integrate new driver arms hands bimanual no hands melodic
shadow-robot/sr_interface pull request #471
Opened 2020-02-19 16:53 UTC by carebare47

## Proposed changes

Switches to the new ur10 driver

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [ ] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [ ] Tested on real hardware (if appropriate)
￼

2020-02-20 10:38 UTC, giusebar commented on sr_robot_launch/launch/sr_hardware_control_loop.launch
> +    <!--param name="$(arg arm_id)_sr_ur_robot_hw/robot_program_path" type="str" value="$(find sr_ur_bringup)/robot_programs/"/-->
should we remove this commented stuff?

2020-02-20 10:39 UTC, giusebar requested changes

2020-02-20 10:39 UTC, giusebar commented on sr_robot_launch/launch/sr_hardware_control_loop.launch
> +    <!--rosparam command="load" file="$(find sr_ur_robot_hw)/config/$(arg arm_id)_sr_ur_robot_hw.yaml"/-->
here as well?

2020-03-02 14:58 UTC, giusebar submitted a review, later dismissed

2020-03-02 14:58 UTC, giusebar commented on sr_robot_launch/launch/sr_bimanual_hardware_control_loop.launch
> +  <param name="ra_sr_ur_robot_hw/non_blocking_read" type="bool" value="true"/>
we should move this non-blocking params in the yaml files

2020-03-02 14:58 UTC, giusebar commented on sr_robot_launch/launch/sr_hardware_control_loop.launch
> +  <param name="$(arg arm_prefix)_sr_ur_robot_hw/non_blocking_read" type="bool" value="true"/>
here too

2020-03-03 13:29 UTC, beatrizleon approved these changes

2020-03-03 13:31 UTC, merged