Updating hand tests
shadow-robot/sr_interface pull request #566
Opened 2020-11-04 16:24 UTC by georgiablanco

## Proposed changes

Please explain the changes you made. Add pictures or videos to explain them better if appropiate.

## Types of changes

What types of changes does your code introduce?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

Put an x in the boxes that apply. You can also fill these out after creating the PR. This is a reminder of what we should look for before merging this code. I have:

- [ ] Read and follow the [contributing guidelines](https://github.com/shadow-robot/sr_documentation/blob/master/CONTRIBUTING.md).
- [ ] Checked that all tests pass with my changes
- [ ] Added tests (automatic or manual) that prove the fix is effective or that the feature works
- [ ] Added necessary documentation (if appropriate)
- [ ] Added the corresponding license to each file and add the current year of any one that you modified.
- [ ] Tested on real hardware (if appropriate)
￼

2020-11-04 16:27 UTC, joannaphillips45 approved these changes

2020-11-04 16:47 UTC, biofotis approved these changes, later dismissed

2020-11-05 09:17 UTC, mikramarc requested changes

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +hand_type = rospy.get_param('/test_hand_joint_movement/test_sim/hand_type', "hand_e_plus")
please avoid global variables if possible

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +if hand_type == 'hand_e_plus':
maybe if hand_e_plus is the default then lets make this the other way around? Non default should switch to default if identical

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +ConfigPack = {
global as well, also please use "variable_name" convention and please give this more explanatory name then configpack

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +        if hand_id == 'lh':
elif
also, if user provides different hand_id, throw exception as id is unknown

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +if hand_type == 'hand_e_plus':
also, if used provides unknown hand_type, please throw exception

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +
please remove this line so related operations are grouped together

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +        for k in open_joints_target:
please use key instead of k. easier to read code when you dont have single letters around it.
https://docs.quantifiedcode.com/python-anti-patterns/maintainability/using_single_letter_as_variable_name.html

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +        joints_target = ConfigPack[hand_type]
please rename to sth like "pack_joints_target_no_id" or something similarily explanatory

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +
keep relevant code bits together without empty lines

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +        for k, v in joints_target.items():
key, value

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +        expected_and_final_joint_value_diff = 0
since this code is duplicated in another method, would be nice to wrap it in a method.

2020-11-05 09:17 UTC, mikramarc commented on sr_robot_launch/test/test_hand_joint_movement.py
> +        rospy.init_node('test_sim', anonymous=True)
please move this to __main__

2020-11-05 12:58 UTC, mikramarc approved these changes

2020-11-05 12:58 UTC, merged