F integrated autodetection
shadow-robot/sr_interface pull request #667
Opened 2021-08-20 13:44 UTC by mikramarc

## Proposed changes

Contains all changes needed for autodetection integration.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added automated tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2021-09-02 20:01 UTC, beatrizleon requested changes

2021-09-02 20:01 UTC, beatrizleon commented on sr_robot_launch/launch/sr_hardware_control_loop.launch
> +    <include file="$(find sr_robot_launch)/launch/load_robot_description.launch">
```suggestion
  <include file="$(find sr_robot_launch)/launch/load_robot_description.launch">
```

2021-09-02 20:01 UTC, beatrizleon commented on sr_robot_launch/launch/sr_ur_arm_box.launch
> +    <include file="$(find sr_robot_launch)/launch/sr_simulation_control_loop.launch">
Have you tested this with arm and box in sim?

2021-09-02 20:01 UTC, beatrizleon commented on sr_robot_launch/launch/sr_ur_arms_hands.launch
>    <!-- SIMULATED ROBOTS -->
Should we move this comment right before the if for sim?

2021-09-02 20:01 UTC, beatrizleon commented on sr_robot_launch/launch/srhand.launch
> +  <group if="$(eval sim and not external_control_loop)">
Check these conditions

2021-09-02 20:01 UTC, beatrizleon commented on sr_robot_launch/launch/srhand.launch
> +  <group if="$(eval not sim and not external_control_loop)">
Check these conditions

2021-09-03 09:27 UTC, mikramarc commented on sr_robot_launch/launch/sr_ur_arms_hands.launch
>    <!-- SIMULATED ROBOTS -->
So I left it here because those args are only relevant to sim. But if it's clearer I can move it down, no problem.

2021-09-03 09:29 UTC, mikramarc commented on sr_robot_launch/launch/sr_ur_arm_box.launch
> +    <include file="$(find sr_robot_launch)/launch/sr_simulation_control_loop.launch">
yep, works fine in sim.

2021-09-03 12:05 UTC, beatrizleon approved these changes

2021-09-03 12:06 UTC, beatrizleon commented
The documentation will be added in another user story. So maybe tick the first box?

2021-09-03 12:08 UTC, mikramarc commented
@beatrizleon Done

2021-09-09 11:04 UTC, giusebar approved these changes

2021-09-09 11:16 UTC, merged