Update demo
shadow-robot/sr_interface pull request #683
Opened 2021-11-05 16:27 UTC by georgiablanco

## Proposed changes

Update demo

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added automated tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2021-11-08 08:55 UTC, mikramarc requested changes

2021-11-08 08:55 UTC, mikramarc commented on sr_demos/scripts/sr_demos/demo.py
> +                if time.time() < wake_time + 15:
what is this 15? Please put that in a const variable at least so there are no "magic numbers" floating around

2021-11-08 09:04 UTC, biofotis approved these changes

2021-11-08 15:00 UTC, biofotis approved these changes

2021-11-09 14:41 UTC, mikramarc approved these changes

2021-11-15 15:04 UTC, biofotis approved these changes

2021-11-15 15:04 UTC, merged