Avoid error called wait_for_result when no goal exists
shadow-robot/sr_interface pull request #734
Opened 2022-03-23 16:17 UTC by jeferrandiz98

## Proposed changes

Changes to avoid this error:
![image](https://user-images.githubusercontent.com/62122095/159745524-0fb8bfde-d064-4967-a3ae-51a4e2bd4000.png)
This time it is checked if an action is running and it will not wait for the result in case it is not.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-03-24 12:28 UTC, bdenoun requested changes

2022-03-24 12:28 UTC, bdenoun commented on sr_robot_commander/src/sr_robot_commander/sr_robot_commander.py
> +            if not self.action_is_running(i):
Could we make the `i` variable a bit more explicit please? :)

2022-03-25 10:25 UTC, giusebar approved these changes

2022-03-30 09:30 UTC, bdenoun approved these changes

2022-03-30 09:30 UTC, merged