Adding URsim helper
shadow-robot/sr_interface pull request #767
Opened 2022-09-11 21:26 UTC by devops-shadow

## Proposed changes

Adding a helper to reset program in URsim as robotcommander drops the connection and breaks the tests

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-09-12 07:47 UTC, maxzieba requested changes

2022-09-12 07:47 UTC, maxzieba commented on sr_robot_launch/test/ur_arm_helper.py
> +        raise
this can be wrapped to a function with side as parameter

2022-09-12 07:47 UTC, maxzieba commented on sr_robot_launch/test/ur_arm_helper.py
> +            response_left = service_call()
you're not using response_left so it can be removed to a bare 'service_call'

2022-09-12 07:47 UTC, maxzieba commented on sr_robot_launch/test/ur_arm_helper.py
> +            print("Resending program for left arm")
rospy.loginfo?

2022-09-12 07:50 UTC, maxzieba commented on sr_robot_launch/test/ur_arm_helper.py
> +        raise
why the raise?

2022-09-15 13:14 UTC, bdenoun commented on sr_robot_launch/test/ur_arm_helper.py
> +        if response_left.program_running is False:
Please change this to `if not response_left.program_running`

2022-09-15 13:14 UTC, bdenoun commented on sr_robot_launch/test/ur_arm_helper.py
> +        rospy.logerr("Service call failed for left arm %s", e)
please use f-strings

2022-09-15 13:29 UTC, bdenoun commented on sr_robot_launch/test/ur_arm_helper.py
> +            print("Resending program for right arm")
please use ros logging

2022-09-15 13:29 UTC, bdenoun commented on sr_robot_launch/test/ur_arm_helper.py
> +        rospy.logerr("Service call failed for right arm %s", e)
please use f-strings

2022-09-15 13:29 UTC, bdenoun commented on sr_robot_launch/test/ur_arm_helper.py
> +    r = rospy.Rate(1)
please make this r more meaningful

2022-09-26 22:32 UTC, closed without merging